In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#文字列の操作

In [ ]:
# 問題3 文字列の代入(format/f-strings)
# 以下の文章の「〇〇」に対して.format()とf-stringsを使って代入しましょう。
# 「私は〇〇です。〇〇出身です。」

In [ ]:
# 問題4 エスケープ文字
# 次の文字列を句読点で改行しましょう。

# 「いつもの帰り道とは違うルートで帰ってみようかな。迷子にならないか心配だけど。」
# ↓
# 「いつもの帰り道とは違うルートで帰ってみようかな。
# 迷子にならないか心配だけど。」

In [ ]:
# 問題5 書式化
# 16.0という値を次の書式で表示しましょう。

# 符号付き10進数

# 符号付き16進数

# 10進浮動小数点

In [ ]:
# 問題6 大文字・小文字への変換
# 以下の文字列を小文字→大文字、大文字→小文字への変換を行いましょう

# 'hello'
# 'WORLD'

In [ ]:
# 問題7 分割
# こちらの文章を改行部分で分割しましょう。

# 「こんにちは。\n私はAIのロボットです。」

In [51]:
# 問題8 結合
# 以下のリスト内に入っている文字列を結合して一つの文にしましょう。

# messages = ['こんにちは。', '私はAIのロボットです。']

In [165]:
# 問題9 空白除去
# 文のはじめと最後にある空白を除去しましょう。

# 「　いつも食べるここのケーキはとても美味しいね。　」

In [59]:
# 問題10 置換
# 以下の文の「晴れ」を「雨」に置換してください。

# 「今日は晴れですね。」 

In [63]:
# 問題11 文字列検索
# 以下のフレーズの中から「夜空」を検索し、その位置を出力しましょう。

# 「今日はとても夜空が綺麗だ。」

In [164]:
# 問題12 型変換
# 以下のデータ型を文字列型に変換しましょう。

# int:x = 1
# float: y = 1.52
# list: z = [1, 2, 3]
# dict: a = dict(name='john', birth='US')

In [81]:
# 問題13 包含関係
# 以下の文字列Aが文字列Bに含まれているか確認しましょう。

# A: 'sba', B: 'gasba'
# A: 'xdh', B: 'orweit'

#リスト

In [87]:
# 問題14 特定の値を抽出
# 次の配列データの中から、先頭から2つ目の値と最後の値をそれぞれ出力しましょう。
# また2を配列の一番最後に追加しましょう。

# numbers = [0, 3, 8, -4, 9, 1]

In [97]:
# 問題15 特定の値を挿入(insert)
# 先ほどのnumbersリストの先頭に5を挿入しましょう。
# また最後から一つ手前に-3を挿入しましょう

# numbers = [0, 3, 8, -4, 9, 1]

In [103]:
# 問題16 特定の値を削除(remove, pop)
# 先ほどのリストから一つ目の5と最後から3番目の要素を削除しましょう。

# numbers = [5, 0, 3, 8, -4, 9, 1, 5, 2]

In [110]:
# 問題17 フィルター
# 次の、偶数のみを返す関数とfilter()を用いて先ほどのnumbersリストから偶数のみを取り出したリストを作成しましょう。

# def isEven(number):
#     if number % 2 == 0:
#         print(f'This number, {number} is even!')
#         return True
#     else:
#         print(f'This number, {number} is odd!')
#         return False

# numbers = [5, 0, 3, 8, -4, 9, 1, 5, 2]

In [117]:
# 問題18 引数と一致する要素のインデックス
# 先ほどのnumbersリストの中から要素が-4のインデックスを取得しましょう。
# numbers = [5, 0, 3, 8, -4, 9, 1, 5, 2]

In [127]:
# 問題19 ソート(昇順/降順)
# 先ほどのnumbersリストの順序を昇順/降順にそれぞれ並び替えましょう。
# numbers = [5, 0, 3, 8, -4, 9, 1, 5, 2]

#辞書

In [139]:
# 問題20 要素の削除(pop/clear)
# 以下の辞書データからpopメソッドを使って,
# 要素Aと要素Bを削除しましょう．
# またclearメソッドを使って,全ての要素を削除しましょう．

# dictionary = {
#     'A': '今西',
#     'B': '航平',
#     'C': '男性',
#     'D': '東京都',
#     'E': '海外旅行',
# }

In [166]:
# 問題21 情報の取得(keys(), values(), items())
# 以下の辞書データから次の処理を行いましょう。

# キーのみの表示
# 値の中に男性という文字列が存在するか
# 全てのキーと値の表示

# dictionary = {
#     'A': '今西',
#     'B': '航平',
#     'C': '男性',
#     'D': '東京都',
#     'E': '海外旅行',
# }

In [176]:
# 問題22 辞書内の要素検索
# 以下の辞書データからキーCとEに対応する値を表示しましょう。

# dictionary = {
#     'A': '今西',
#     'B': '航平',
#     'C': '男性',
#     'D': '東京都',
#     'E': '海外旅行',
# }

#制御構文(if文)

In [185]:
# 問題23 if文を使って条件分岐
# if文を使って以下の処理を実装してください。

# int型の変数: num
# numが以下の条件の時、コロン右側の文字列を出力する

# numが正の値の場合：　正の値です
# numが0の場合：0です
# numが負の値の場合: 負の値です

In [191]:
# 問題24 論理演算子を使って複数条件の指定
# 以下の条件分岐に対応する実装を行ってください。

# aは整数
# aが0以上10未満かつ偶数: 一桁の偶数です
# aが0未満かつ奇数：負の奇数です
# それ以外: 整数です

#制御構文(for文)

In [197]:
# 問題25 リストから順に表示
# リスト型の変数から順に名前を出力しましょう。

# names = (['John', 'Kevin', 'Louis'])

In [239]:
# 問題26 range関数を使う
# range関数を用いて0~9を出力しましょう。

In [216]:
# 問題27 ループの途中で強制終了 -  break文
# 問題26の処理に追加でi=6の時「BREAK!」と出力してループを抜け出すよう実装しましょう。

In [218]:
# 問題28 ループの途中で特別な処理
# 問題26の処理に追加でi=3の時のみ出力結果が出ないように実装しましょう。 - continue文

In [240]:
# 問題29 複数のリストを同時に処理
# 2つの変数(lasts=['加藤', '佐藤', '田中'], firsts=['雄一', '拓也', '太郎'])を用意してリストから姓名を同時に出力しましょう。

# lasts=['加藤', '佐藤', '田中']
# firsts=['雄一', '拓也', '太郎']

In [227]:
# 問題30 リストと同時にインデックス情報の取得
# 変数(lasts=['加藤', '佐藤', '田中'])を用意して「xx番のyyです。」と出力しましょう

In [268]:
# 問題31 内包表記
# 以下の2つのパターンで0から9未満となる2の倍数が入ったリスト([0, 2, 4, 6, 8])を作成しましょう。

# 空のリストnumsを予め用意しforループ内で.append()関数を用いて要素を追加する
# 1行で同様のリストnumbersを作成する

#例外処理

In [293]:
# 問題32 
# 0で割ったときにエラーと出力
# 10をある数字numで割った時の結果を出力しましょう
# 0で割った場合(割れない)にエラーと出力しましょう

In [299]:
# 問題33 ZeroDivisionErrorの呼び出し
# 10をある数字numで割った時の結果を出力しましょう(try節)
# 0で割った場合(割れない)にZeroDivisionErrorでエラーを出力しましょう(except節)

In [310]:
# 問題34 そのほかのErrorの呼び出し(分けて記述)
# 次のdivide()関数では変数a, bがそれぞれ数値の場合に正常に数値計算が行われます。

# def divide(a, b):
#     try:
#         print(f'{a}を{b}で割ると{a / b}です。')
#     except ZeroDivisionError as e:
#         print(e)

# aまたはbが文字列の場合(数値の型とは異なる場合)の例外処理(TypeError)をexcept節を追加して実装しましょう。

In [314]:
# 問題35 通常終了時に行う処理
# 先ほどのdivide()関数で例外処理が発生しなかった場合に「正常に終了しました。」と表示されるよう(else節)にしましょう。

In [324]:
# 問題36 例外も含めた終了時に行う処理
# 先ほどのdivide()関数で例外処理の発生した有無に限らず「全ての処理が終了しました。」と表示されるよう(finally節)にしましょう。

In [342]:
# 問題37 例外をスルーする
# こちらのdivide()関数でTypeErrorの例外処理の発生した場合スルーするようにしましょう。

# def divide(a, b):
#     try:
#         print(f'{a}を{b}で割ると{a / b}です。')
#     except ZeroDivisionError as e:
#         print(e)
#     except TypeError as e:
#         print(e)
#     finally:
#         print('全ての処理が終了しました。')

#クラス

In [350]:
# 問題37 classの基礎
# Personクラスを用意し、クラス変数としてnationality='Japan'、クラスメソッドとして.say_hello()実装しましょう。
# ただしこちらのメソッドでは「こんにちは、私の国籍は{self.nationality}です。」と出力するようにしましょう。

In [367]:
# 問題38 コンストラクタの設定
# 続いて、先ほどのPersonクラスにコンストラクタ(インスタンス生成時に呼び出される関数)を使って、引数に名前を設定して.nameというインスタンス変数を持たせましょう。
# またsay_my_name()という自分の名前を出力するクラスメソッドを実装しましょう。

In [382]:
# 問題39 クラスの継承
# 先ほどのPersonクラスを継承したKidクラスを作成しましょう。
# その際に自分の年齢を出力するようにクラスメソッドsay_hello(age)(年齢を引数)を変更しましょう。
# またそれらがきちんと動作しているか次のコードで確認しましょう。

In [392]:
# 問題40 privateとpublic
# 先ほどのPersonクラス内のクラス変数のnationalityを__nationalityへ変更し外部から呼び出せないprivateな変数になっていることを確認しましょう。
# また同様に say_my_name()関数も__ say_my_name()と修正し、外部から呼び出せないことを確認しましょう。

#ファイル操作

In [399]:
# 問題41 ファイル操作の基本(open, read, close)
# まず以下のテキストファイルを用意しましょう。

# samples/08_41_sample.txt

# はじめまして、
# こちらはいまにゅうチャンネルです。
# Pythonを使いこなして色んなことができるように、
# 一緒に学んでいきましょう。
# 以下の処理を行ってテキストファイルからテキストデータを取得して出力しましょう

In [405]:
# 問題42 with構文 - よく使う構文
# 先ほどのテキストデータを取得する処理をwith構文を使って実装しましょう

In [415]:
# 問題43 jsonモジュール
# jsonモジュールを使って以下のjsonファイルを読み込みましょう。

#Matplotlib 57~64

In [420]:
# 問題57 折れ線グラフ
# 以下のようにNumpyでデータを生成して, Matplotlibで折れ線グラフを作成してください。

# import numpy as np

# data = np.random.randint(0, 100, size=(50, 2))

In [424]:
# 問題58 散布図
# 以下のようにNumpyでデータを生成して, 散布図を作成してください。

# import numpy as np
# data = np.random.randint(0, 50, size=(2, 100))


In [434]:
# 問題59 棒グラフ
# 以下のようにNumpyでデータを生成して, 2種類の棒グラフ(縦・横)を作成してください。

# import numpy as np

# x = [1, 2, 3, 4, 5]
# data = np.random.randint(0, 100, size=(5,))
# labels = ['Math', 'Physics', 'Chemistry', 'English', 'History']

In [438]:
# 問題60 ヒストグラム
# 以下のようにNumpyでデータを生成して, ヒストグラムを作成してください。

# import numpy as np
# data = np.random.randint(0, 100, size=(20,))

In [442]:
# 問題61 軸の名前と範囲指定
# 以下のように作成したグラフの軸にタイトル(x軸: Height [cm], y軸: Weight [kg])と範囲(x軸: 110〜210, y軸: 20〜120)を追加してください。

# import numpy as np

# male_ht = np.random.randint(150, 200, size=(50,))
# male_wt = np.random.randint(50, 110, size=(50, ))
# female_ht = np.random.randint(130, 170, size=(50,))
# female_wt = np.random.randint(30, 80, size=(50, ))

# plt.scatter(male_ht, male_wt, label='male')
# plt.scatter(female_ht, female_wt, label='female')

In [445]:
# 問題62 色の設定
# 以下のように作成した散布図のマーカの色を(男性: skyblue, 女性: pink)に変更してください。

# import numpy as np

# male_ht = np.random.randint(150, 200, size=(50,))
# male_wt = np.random.randint(50, 110, size=(50, ))
# female_ht = np.random.randint(130, 170, size=(50,))
# female_wt = np.random.randint(30, 80, size=(50, ))

# plt.scatter(male_ht, male_wt, label='male')
# plt.scatter(female_ht, female_wt, label='female')

In [447]:
# 問題63 マーカー種類の指定
# 以下のように作成したグラフのマーカーを(男性: ▷, 女性: ◁)に変更してください。

# import numpy as np

# male_ht = np.random.randint(150, 200, size=(50,))
# male_wt = np.random.randint(50, 110, size=(50, ))
# female_ht = np.random.randint(130, 170, size=(50,))
# female_wt = np.random.randint(30, 80, size=(50, ))

# plt.scatter(male_ht, male_wt, label='male')
# plt.scatter(female_ht, female_wt, label='female')

In [449]:
# 問題64 グラフを画像ファイルで出力
# 以下のようにMatplotlibで折れ線グラフを作成し、その結果をPNG形式の画像ファイルで保存して下さい。

# import numpy as np

# data = np.random.randint(0, 100, size=(50, 2))
# plt.plot(data)

#Numpy

In [9]:
# 1問目：ベクトルの定義
# np.array()を使って次のベクトルを定義してください。
# a = [1,2,3,4]

# b = (4,
#      -1,
#      6)

In [12]:
# 2問目：行列の定義
# np.array()を使って次の行列を定義してください。
# c = (3,-2,
#      7,1)

# D = (3,-2,0,1,
#      7,1,-1,2,
#      4,-5,1,3)

In [27]:
# 3問目：ベクトルの作成
# こちらのように規則性のあるベクトルを作成してください
# a = [0,0]
# b=(1,
#    1,
#    1,
#    1,
# )

In [36]:
# 4問目：
# こちらのように規則性のある行列(単位行列)を作成してください

# c = (1,0,0,
#      0,1,0,
#      0,0,1)

# d = (1,0,0,0,
#      0,1,0,0,
#      0,0,1,0,
#      0,0,0,1,
#      )

In [53]:
# 5問目：基本情報の取得
# こちらのベクトルと行列の基本情報(下記項目)を取得してください
# a = [2,3,4]
# b = (1.2,3.5,5.1,
#      -0.3,1.1,-4.5,
#      )

# 形状
# 次元
# データ型
# 要素数

In [81]:
# 6問目：インデックスとスライシング
# こちらのベクトル行列から以下の項目に従ってそれぞれの要素取得してください

# ベクトル
# 3~５つ目まで
# 逆順で

# a = np.array(1,13,2)


# 行列
# １行目全て(3つ)
# ３行１列目(1つ)
# 2~3行目2~3列目(4つ)

# b = (2,4,6,
#      -1,5,-3,
#      0,-2,3)

# a = np.arange(1,13,2)

# ベクトル

# 3~５つ目まで

# 逆順で


# 行列
# b = np.array([[2,4,6],
#               [-1,5,-3],
#               [0,-2,3]])

# １行目全て(3つ)

# ３行１列目(1つ)

# 2~3行目2~3列目(4つ)

In [90]:
# 7問目：四則演算
# こちらの行列の四則演算を行ってください

# 足し算
# (1,3,-2,4) + (2,-1,3,0)

# 引き算
# (1,3,-2,4) - (2,-1,3,0)

# 行列積
# (1,3,-2,4)(2,-1,3,0)

# アダマール積 - 要素同士の(同じ場所同士)の掛け算
# (1,3,-2,4)*(2,-1,3,0)

# a = np.array([[1,3],[-2,4]])
# b = np.array([[2,-1],[3,0]])

# # print(a)
# # print(b)

In [94]:
# 8問目：転置 - 行と列を入れ替える
# こちらのベクトル行列の転置を行ってください

# a = [2,3,4]
# b = (1.2,3.5,5.1,
#      -0.3,1.1,-4.5)

# a = np.array([2,3,4])
# b = np.array([[1.2,3.5,5.1,],
#               [-0.3,1.1,-4.5]])

In [127]:
# 9問目：逆行列

# 下記の値を求めてください

# 行列の行列式の値
# 行列式の値が0出なければその逆行列

# a = (4,-2,
#      1,0) 

# a = np.array([[4,-2],[1,0]])
# print(a)

In [4]:
# 10問目：ブロードキャスト - ベクトル行列計算を簡易的に書けるようになっているもの
# Numpyで定義されたベクトル行列にスカラーをかけた場合の計算結果を確認してください
# ([[4,-2],[1,0]])*0.5
# ([[8,1,5],[-3,0,7]])*2

# a = np.array([[4,-2],[1,0]])
# b = np.array([[8,1,5],[-3,0,-7]])

In [9]:
# 11問目：ベクトルのサイズ変更
# こちらのように定義されたベクトルを次の行列にサイズ変更してください

# d = np.arange(12) - 12個の要素を持つベクトル
# array([0,1,2,3,4,5,6,7,8,9,10,11])


# d = (0,1,2,3,
#      4,5,6,7,
#      8,9,10,11)

# d = np.arange(12)

# ３行４列に変える

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
# 12問目：統計値
# こちらの行列の統計値以下の項目を確認してください

# b = (2,4,6,
#      -1,5,-3,
#      0,-2,3)

# 最大値
# 最小値
# 総和
# 平均
# 分散
# 標準偏差

# b = np.array([[2,4,6],[-1,5,-3],[0,-2,3]])

In [17]:
# 13問目：ユニバーサル関数 - Numpyの配列, ndarrayの全要素に対して要素ごとに演算の処理に従って結果を返す関数

# Numpyに用意されている下記の数理的な関数をこちらの行列にで実装してください

# 平方根
# eの指数関数

# a = (0,1,
#      2,4)

# a = np.array([[0,1],[2,4]])

In [22]:
# 14問目：ユニバーサル関数 
# Numpyに多いされている下記の数理的な関数をこちらの行列にで実装してください

# sin関数
# cos関数

# a = np.array([0,np.pi, np.pi/2,-np.pi/4]).reshape(2,-1)

In [37]:
# 15問目：行列の結合
# 次の行列を使って以下の項目に従い,結合を行ってください

# 縦方向に結合:cで定義
# 縦方向に結合:dで定義

# a = (0,1,-1,
#      2,4,-3,
#      5,-2,7)

# b = (-2,0,1,
#      5,-1,2
#      -6,3,4)

In [35]:
# 16問目：行列の分解
# 先ほどの結合の部分で作成した行列を使って以下の項目に従い分解を行ってください

# 縦方向に分解:cを２つに分けた場合/cを３つに分けた場合
# 横方向に分解:dを２つに分けた場合

In [65]:
# 17問目：
# ここからはNumpyで作成したデータをMatplotlibを使ってグラフ化していきます。下記2つを実装してください
# 0~2πまでの５００サンプルで区切ってsin波,cos波をプロット
# ０〜３０までの整数からランダムに１００サンプルを作成してヒストグラムにする

In [93]:
# 18問目：演習課題
# ここまでの内容を理解しているか確認するために取り組みます。
# 下記の行列の形状を見て計算可能なことを確認した後 c= ab の行列積を計算してください

# a = (-10,-8,-6,
#      -4,-2,0,
#      2,4,6,
#      8,10,12)

# b = (-1,-2,-2,-2,
#      -2,-1,-2,-2,
#      -2,-2,-1,-2)

In [89]:
# 19問目：演習課題
# 先ほど作成した行列cの2行2列目までをdとして取り出し、一度転置した後、逆行列を求めてください。

# cの2行2列目までをdとして取り出し、一度転置した後、逆行列を求めてください。

In [92]:
# 20問目：演習課題
# -100から100までの整数の乱数300サンプルを2つ作成しそれぞれをx軸の値,y軸の値とした場合の散布図をプロットしてください

#Pandas

In [2]:
# 01. データの読み込み
# weather.csvを読み込み、df で定義してください

df = pd.read_csv("/content/weather.csv")
df.head()

年月日  平均気温(℃) 平均気温(℃).1  ... 日照時間(時間)  日照時間(時間).1 日照時間(時間).2
0         NaN      NaN      品質情報  ...      NaN        品質情報       均質番号
1  2019/12/14      9.3         8  ...      8.9           8          1
2  2019/12/15      7.8         8  ...      6.3           8          1
3  2019/12/16      6.9         8  ...      8.9           8          1
4  2019/12/17      8.2         8  ...      0.2           8          1

[5 rows x 28 columns]

In [98]:
# 02. データの中身確認
# 読み込んだデータdfの先頭3行、末尾10行を表示してください。

In [71]:
# 03. 不要な列、行の削除
# 行は先頭のみ、列は、カラム名（列名）が「〇〇.1」「〇〇.2」となっているものを削除したDataFrame df を再定義してください。
# 03. 不要な列、行の削除
# 行は先頭のみ、列は、カラム名（列名）が「〇〇.1」「〇〇.2」となっているものを削除したDataFrame df を再定義してください。

# df.columns - 全カラム名を取ってこれる

In [126]:
# 04. DataFrameに関する情報の取得
# 下記の値を取得してください。

# 各列のデータ型

# DataFrameのサイズ

# 列名

# 行名

RangeIndex(start=3, stop=368, step=1)

In [130]:
# 05. 任意の要素を取得
# dfの 5〜10行目, 3〜6列目（最高気温(℃)〜最深積雪(cm)）の要素を取得してください。

In [3]:
# 06. 条件抽出
# people.csv を読み込みdf_peopleと定義してください。

# その後、下記の条件を満たすDataFrameをそれぞれ抽出してください。
# nationality が America である
# age が 20以上30未満である

df_people = pd.read_csv("/content/people.csv")
df_people

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [181]:
# 07. ユニークな値の抽出
# df_peopleに対して、カラム毎のユニーク（固有）な値を抽出してください。 - xxx.unique()

In [184]:
# 08. 重複除去
# nationalityの列に対し、重複がある値の行を除去したDataFrameを取得してください。

In [70]:
# 09. カラム名変更
# dfに対し、各カラム名の「（単位）」部分を削除したカラム名に変更してください。

In [10]:
# 10. 並び替え
# dfを最高気温が高い順に並び替えてください。

In [26]:
# 11. ダミーデータへの処理
# df_peopleのnationalityカラムをダミー変数に変換してください。

# df_peopleのnationalityカラムをダミー変数に変換してください。 - pd.get_dummies(df_people,columns=["nationality"])

In [28]:
# 12. 欠損値の確認
# dfの欠損値を確認してください。

In [30]:
# 13. 欠損値の補完
# dfの欠損値を全て0で補完してください。

In [34]:
# 14. 欠損値の削除
# dfの欠損値を列方向で削除してください。


In [42]:
# 15. ユニークな値と出現回数
# iris.csvを読み込みdf_irisと定義してください。
# その後、df_irisのClassカラムにおいて、ユニークな値とその出現回数を確認してください。

df_iris = pd.read_csv("/content/iris.csv")

In [51]:
# 16. グループごとの集計
# df_irisの下記各クラスにおけるsepal-length, sepal-width, petal-length, petal-widthの平均値を求めてください。

# Iris-setosa
# Iris-versicolor
# Iris-virginica

In [60]:
# 17. 統計量の確認
# df_irisの各カラムにおける、下記統計量を算出してください。 - print(df_iris.describe())

# 平均値
# 中央値
# 標準偏差
# 最大値
# 最小値

In [59]:
# 18. 折れ線グラフの表示
# dfの先頭50日間おける平均気温、最高気温、最低気温を折れ線グラフ（凡例なし）で可視化してください。
# ※横軸は年月日とすること

In [65]:
# 19. 相関係数の算出
# dfの下記3項目同士の相関係数を算出してください。

# 平均気温
# 降水量の合計
# 日照時間

In [69]:
# 20. データの出力
# 欠損値を0で補完したdfをexport.csvというファイル名でcsvとして出力してください。インデックスの出力は不要です。

#Matplotlib

In [73]:
# 01. 折れ線グラフ
# 以下のコード作成した変数 x と y を用いて折れ線グラフを出力してください。

# x = np.arange(10)
# y = np.random.randint(-10,10,10)

In [76]:
# 02. 散布図
# 以下のコードを作成した変数 x1,x2と y1,y2を用いて散布図を出力してください。

# x1 = np.random.randint(10,20,20)
# x2 = np.random.randint(20,30,20)
# y1 = np.random.randint(50,100,20)
# y2 = np.random.randint(0,40,20)

In [78]:
# 03. ヒストグラム
# 以下のコードで用意したデータを用いてヒストグラムを作成してください

# data = np.random.randint(0,10,10)

In [84]:
# 04. 棒グラフ
# 以下のコードで作成した変数 x と y を用いて棒グラフを出力してください。

# x = ["Sam","John","Kevin","Adam"]
# y = np.random.randint(0,200,4)

In [86]:
# 05. タイトルとラベル
# グラフの詳細制定について編集を行っていきます。
# Matplotlibの公式ドキュメントにあるグラフで設定できる機能を順に試していきます。

# まずは問題１で作成したグラフにタイトルResultを付けて下さい。
# また x 軸にはx axis y 軸には y axisというラベルも付けて下さい。

# x = np.arange(10)
# y = np.random.randint(-10,10,10)
# plt.plot(x,y)

In [88]:
# 06. 軸範囲
# 範囲グラフの軸範囲を指定します。先ほど問題にで作成した散布図を使います。
# こちらのグラフの x 軸の範囲を0~40とし,y軸の範囲を0~120としてください。

# x1 = np.random.randint(10,20,20)
# x2 = np.random.randint(20,30,20)
# y1 = np.random.randint(50,100,20)
# y2 = np.random.randint(0,40,20)

# plt.scatter(x1,y1)
# plt.scatter(x2,y2)


In [91]:
# 07. 対数軸
# 下記のグラフにおいて軸のスケールをlog(対数関数)に調整してみてください

# x = np.linspace(0,10,500)
# y = np.exp(x) - 指数関数

# plt.plot(x,y)

In [95]:
# 08. 凡例
# 以下のコードを実行したグラフに対しsin,cosという判例をつけたグラフを作成してください

# x = np.linspace(0,2*np.pi, 500)
# y1 = np.sin(x)
# y2 = np.cos(x)

# plt.plot(x, y1)
# plt.plot(x, y2)

# plt.ylim(-2,2)

In [98]:
# 09. マーカの種類・サイズ変更

# 以下の散布図のマーカーの種類とサイズを変更してみてください
# マーカ:星,サイズ:80
# マーカ:三角形,サイズ:60
# マーカ:x,サイズ:30

# x1 = np.random.randint(10,35,20)
# x2 = np.random.randint(5,45,20)
# x3 = np.random.randint(0,40,20)
# y1 = np.random.randint(50,100,20)
# y2 = np.random.randint(0,40,20)
# y3 = np.random.randint(20,80,20)

# plt.scatter(x1,y1)
# plt.scatter(x2,y2)
# plt.scatter(x3,y3)

In [103]:
# 10. 注釈
# 以下のゴールで作成したグラフに注釈を加えましょう。
# 最小値となる部分に対して矢印を使ってmin valueというテキストを表示してください.

# data = [5,3,4,2,0,3,2,1,4,6,8,5]

# plt.plot(data)

In [112]:
# 11. 目盛り
# 先ほどのグラフの目盛りは,x軸がゼロから11までの2刻み y軸が0~8まで1刻みとなっています/
# こちらのx軸を1刻み,y軸を2刻みとなるように変更してください。

# data = [5,3,4,2,0,3,2,1,4,6,8,5]

# plt.plot(data)
# plt.annotate("min value",xy = (4.2,0), xytext = (9,1), arrowprops = dict(facecolor = "black",shrink = 0.05))

In [119]:
# 12. グリッド線
# グラフにグリッド線を追加してください

# data = [5,3,4,2,0,3,2,1,4,6,8,5]

# plt.plot(data)

In [126]:
# 13. 複数グラフの表示
# 以下のデータに対し,異なる形状のグラフを横並びに3つ表示してください。

# names = ["Sam","John","Kevin","Adam"]
# values = [60,170,10,120]
# 棒グラフ(plt.bar())
# 散布図(plt.scatter())
# 折れ線グラフ(plt.plot())

# ただし3つのグラフを表示する全体のグラフサイズは横9インチ,横3インチとしてください

In [135]:
# 14. ヒートマップ 
# 以下のコードで用意した10*10のデータに対し、最小値0が白色で最大値1が青色となるカラーマップ使ってヒートマップを作成してください。

# data = np.random.rand(10,10)


In [139]:
# 15. 3次元グラフ
# 次のデータを使って3次元に点をプロットしてみてください。
# こちらのデータは z軸真上方向に螺旋のような動きをしながら伸びていくものとなっております。

# theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
# z = np.linspace(-2,2,100) 
# r = z**2+1
# x = r * np.sin(theta)
# y = r * np.cos(theta)

# 3次元グラフに必要モジュール

# from mpl_toolkits.mplot3d import Axes3D

In [148]:
# 16. 円グラフ
# 以下にに用意したデータを使って円グラフを作成してください
 
# x = np.array([100,200,300,400,500])
# labels = ["Apple","Banana","Orange","Grape","Strawberry"]
# colors = ["red","yellow","orange","purple","pink"]

In [ ]:
# 17. GUIウィジェット
# 以下のコードで作成した散布図上にカーソルを持っていくとカーソルの座標が表示されるようにしてください。

# fig = plt.figure(figsize=(8,6))
# ax = fig.add_subplot(111,facecolor="#FFFFCC")

# x,y = 4*(np.random.rand(2,100) -.5)
# ax.plot(x,y,"o")
# ax.set_xlim(-2,2)
# ax.set_ylim(-2,2)

# plt.show()

In [153]:
# 18. 演習問題1
# 下の2つのグラフを一つのグラフ(figsize=(9,6)として縦に二つ並べた形に修正してください。

# グラフ1
# x = np.arange(10)
# y = np.random.randint(-10,10,10)
# plt.plot(x,y)
# plt.title("Result")
# plt.xlabel("x axis")
# plt.ylabel("y axis")

# グラフ2
# x = ["Sam","John","Kevin","Adam"]
# y = np.random.randint(0,200,4)
# plt.bar(x,y)

In [163]:
# 19. 演習問題2
# 次のデータを使って以下の図のようなグラフを作成してください

# label = "Chips","Hotdogs","Cookies","Chocolates"
# sizes = [15,30,45,10]

# なお、円グラフの特徴は以下になります
# 円グラフ(Hogsのみ半径10%分のオフカット)
# 影あり
# 少数点以下1桁%まで表示する
# 0時の位置から反時計回りに始まる

In [176]:
# 20. 演習問題3
# 次の3つの異なるデータを使って以下の図のような積み上げタイプのヒストグラムを作成してください。
# ただしビンの数は10としています

# mu1,sigma1 = 100,15
# mu2,sigma2 = 90,20
# mu3,sigma3 = 110,10

# x1 = mu1 + sigma1 * np.random.randn(100)
# x2 = mu2 + sigma2 * np.random.randn(100)
# x3 = mu3 + sigma3 * np.random.randn(100)